dataset: "mvtec"
data_path: "/home/zhy/anomaly/datasets/mvtec/"
resize: [hight,width]
imagesize: [channel, hight,width]
_CLASSNAMES: [ "bottle", "cable", "capsule", "carpet", "grid",
               "hazelnut", "leather",  "metalnut", "pill", "screw",
               "tile",  "toothbrush",  "transistor",  "wood",  "zipper" ]
dataset_len: 15
low_shot: False
distance: True